CREATE TABLE tb_banco(
   codigo VARCHAR(6) NOT NULL PRIMARY KEY
  ,nome   VARCHAR(54) NOT NULL
);
INSERT INTO tb_banco(codigo,nome) VALUES ('001','Banco do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('341','Banco Itaú S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('033','Banco Santander (Brasil) S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('356','Banco Real S.A. (antigo)');
INSERT INTO tb_banco(codigo,nome) VALUES ('652','Itaú Unibanco Holding S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('237','Banco Bradesco S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('745','Banco Citibank S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('399','HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO tb_banco(codigo,nome) VALUES ('104','Caixa Econômica Federal');
INSERT INTO tb_banco(codigo,nome) VALUES ('389','Banco Mercantil do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('453','Banco Rural S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('422','Banco Safra S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('633','Banco Rendimento S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('246','Banco ABC Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('025','Banco Alfa S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('641','Banco Alvorada S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('029','Banco Banerj S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('038','Banco Banestado S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('000','Banco Bankpar S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('740','Banco Barclays S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('107','Banco BBM S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('031','Banco Beg S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('096','Banco BM&F de Serviços de Liquidação e Custódia S.A');
INSERT INTO tb_banco(codigo,nome) VALUES ('318','Banco BMG S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('752','Banco BNP Paribas Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('248','Banco Boavista Interatlântico S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('036','Banco Bradesco BBI S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('204','Banco Bradesco Cartões S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('225','Banco Brascan S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('044','Banco BVA S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('263','Banco Cacique S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('473','Banco Caixa Geral – Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('222','Banco Calyon Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('040','Banco Cargill S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M08','Banco Citicard S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M19','Banco CNH Capital S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('215','Banco Comercial e de Investimento Sudameris S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('756','Banco Cooperativo do Brasil S.A. – BANCOOB');
INSERT INTO tb_banco(codigo,nome) VALUES ('748','Banco Cooperativo Sicredi S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('505','Banco Credit Suisse (Brasil) S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('229','Banco Cruzeiro do Sul S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('003','Banco da Amazônia S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('083-3','Banco da China Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('707','Banco Daycoval S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M06','Banco de Lage Landen Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('024','Banco de Pernambuco S.A. – BANDEPE');
INSERT INTO tb_banco(codigo,nome) VALUES ('456','Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('214','Banco Dibens S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('047','Banco do Estado de Sergipe S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('037','Banco do Estado do Pará S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('041','Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('004','Banco do Nordeste do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('265','Banco Fator S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M03','Banco Fiat S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('224','Banco Fibra S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('626','Banco Ficsa S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('394','Banco Finasa BMC S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M18','Banco Ford S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('233','Banco GE Capital S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('734','Banco Gerdau S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M07','Banco GMAC S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('612','Banco Guanabara S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M22','Banco Honda S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('063','Banco Ibi S.A. Banco Múltiplo');
INSERT INTO tb_banco(codigo,nome) VALUES ('M11','Banco IBM S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('604','Banco Industrial do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('320','Banco Industrial e Comercial S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('653','Banco Indusval S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('630','Banco Intercap S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('249','Banco Investcred Unibanco S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('184','Banco Itaú BBA S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('479','Banco ItaúBank S.A');
INSERT INTO tb_banco(codigo,nome) VALUES ('M09','Banco Itaucred Financiamentos S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('376','Banco J. P. Morgan S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('074','Banco J. Safra S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('217','Banco John Deere S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('065','Banco Lemon S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('600','Banco Luso Brasileiro S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('755','Banco Merrill Lynch de Investimentos S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('746','Banco Modal S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('151','Banco Nossa Caixa S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('045','Banco Opportunity S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('623','Banco Panamericano S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('611','Banco Paulista S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('643','Banco Pine S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('638','Banco Prosper S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('747','Banco Rabobank International Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M16','Banco Rodobens S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('072','Banco Rural Mais S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('250','Banco Schahin S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('749','Banco Simples S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('366','Banco Société Générale Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('637','Banco Sofisa S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('464','Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('082-5','Banco Topázio S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M20','Banco Toyota do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('634','Banco Triângulo S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('208','Banco UBS Pactual S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('M14','Banco Volkswagen S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('655','Banco Votorantim S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('610','Banco VR S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('370','Banco WestLB do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('021','BANESTES S.A. Banco do Estado do Espírito Santo');
INSERT INTO tb_banco(codigo,nome) VALUES ('719','Banif-Banco Internacional do Funchal (Brasil)S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('073','BB Banco Popular do Brasil S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('078','BES Investimento do Brasil S.A.-Banco de Investimento');
INSERT INTO tb_banco(codigo,nome) VALUES ('069','BPN Brasil Banco Múltiplo S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('070','BRB – Banco de Brasília S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('477','Citibank N.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('081-7','Concórdia Banco S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('487','Deutsche Bank S.A. - Banco Alemão');
INSERT INTO tb_banco(codigo,nome) VALUES ('751','Dresdner Bank Brasil S.A. – Banco Múltiplo');
INSERT INTO tb_banco(codigo,nome) VALUES ('062','Hipercard Banco Múltiplo S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('492','ING Bank N.V.');
INSERT INTO tb_banco(codigo,nome) VALUES ('488','JPMorgan Chase Bank');
INSERT INTO tb_banco(codigo,nome) VALUES ('409','UNIBANCO – União de Bancos Brasileiros S.A.');
INSERT INTO tb_banco(codigo,nome) VALUES ('230','Unicard Banco Múltiplo S.A.');
